# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "nuvoprog-${version}";
  version = "2019-05-27";
  rev = "4505313bf6875dc48349e8820b514dab2a84cb4f";

  goPackagePath = "github.com/erincandescent/nuvoprog";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/erincandescent/nuvoprog.git";
    sha256 = "03j79hkh30754hcmi88cq9ivsp41rw4ll3vi4l8s5p41zz182pl5";
  };

  goDeps = ./deps.nix;

  meta = {
    description = "Nuvoton microcontroller programming tools";
    homepage = "https://github.com/erincandescent/nuvoprog";
    license = stdenv.lib.licenses.asl20;
  };

  # fortify causes cgo build errors
  hardeningDisable = [ "fortify" ];
}
