# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/fatih/color";
    fetch = {
      type = "git";
      url = "https://github.com/fatih/color";
      rev = "3f9d52f7176a6927daacff70a3e8d1dc2025c53e";
      sha256 = "165ww24x6ba47ji4j14mp3f006ksnmi53ws9280pgd2zcw91nbn8";
    };
  }
  {
    goPackagePath = "github.com/karalabe/hid";
    fetch = {
      type = "git";
      url = "https://github.com/karalabe/hid";
      rev = "12a701bced72dabdf5ca67132ccfa1b6cc60c2a7";
      sha256 = "0gfbl0mpl5y4znx6w6k66jbggdj4lc7db467dqa6qp9aswxzjbad";
    };
  }
  {
    goPackagePath = "github.com/spf13/cobra";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/cobra";
      rev = "8d114be902bc9f08717804830a55c48378108a28";
      sha256 = "1ipmdjwqxyvj6cv33xm1m4ngyx49jsnp8n9jd8fjbkng8aw3q4al";
    };
  }
  {
    goPackagePath = "github.com/spf13/pflag";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/pflag";
      rev = "298182f68c66c05229eb03ac171abe6e309ee79a";
      sha256 = "1cj3cjm7d3zk0mf1xdybh0jywkbbw7a6yr3y22x9sis31scprswd";
    };
  }
]
